#本机 配置文件#
#模拟航路：SURF应用场景  本机后起飞
#step：地面
APP: SURF
basic:
  ICAO: 5843be           #ICAO码
  Flight_ID: '3U8894'     #航班号
  Flight_24bit_addr: 0   #24位地址 默认为0
  Altitude: 0        #压强高度 单位m
  Radio_Altitude: 0      #几何高度 默认为0
  North_South_Velocity: 0     #南北速度 单位km/h 初始化0
  East_West_Velocity: 0       #东西速度 单位km/h 初始化0
  Vertical_Speed: 0     #垂直速度 默认为0
  Way_Point:            #所有航路点信息
    point1:
      - ONEBA     #飞机降落点
      - 103.9617
      - 30.5906
      - 0
      - 0              #高度
    point2:
      - ONEBA     #飞机终点
      - 103.9649
      - 30.5910
      - 82.8750
      - 0              #高度
  Ground_Speed: 40      #地速 单位km/h
  Flight_Length: 38.9     #飞机长度 单位m
  Flight_Width: 35.8      #飞机宽度 单位m
  NACV: 4    #速度不确定度 默认为6
  NACp: 7    #位置不确定度 默认为0
  NIC: 1
  SIL: 2
extra:
  delay_time: 0          #起飞延迟 单位s
  fre_transmit_data: 1     #本机数据发送频率 单位s